#!/bin/bash
id=$QUERY_STRING
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Bash as CGI"
echo "</title></head><body>"
echo "<h1>Service log $id</h1>"
echo ""
echo "<pre> $(docker service logs $id ) </pre>"
echo "<h1>Service details $id</h1>"
echo ""
echo "<pre> $(docker service inspect $id ) </pre>"

echo "<center>Information generated on $(date)</center>"
echo "</body></html>"

